package com.daullim.backend.domain.visit.entity;

import jakarta.persistence.CollectionTable;
import jakarta.persistence.Column;
import jakarta.persistence.ElementCollection;
import jakarta.persistence.Entity;
import jakarta.persistence.FetchType;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.JoinColumn;
import jakarta.persistence.ManyToOne;
import jakarta.persistence.PrePersist;
import jakarta.persistence.Table;
import java.time.Instant;
import java.util.LinkedHashSet;
import java.util.Set;

/** 교체 대상 1건. 내용연수 경과 시 BE가 roomCount만큼 자동 생성하되 autoGenerated로 현장 입력과 구분한다. */
@Entity
@Table(name = "replacement_items")
public class ReplacementItem {

  @Id
  @GeneratedValue(strategy = GenerationType.IDENTITY)
  @Column(name = "replacement_item_id")
  private Long id;

  @ManyToOne(fetch = FetchType.LAZY, optional = false)
  @JoinColumn(name = "visit_id", nullable = false)
  private Visit visit;

  @Column(name = "item_seq", nullable = false)
  private short itemSeq;

  @Column(name = "replace_reason_cd", length = 20, nullable = false)
  private String replaceReasonCode;

  /** 방전일 때만 채워진다. DB CHECK가 그 대응을 강제한다. */
  @Column(name = "battery_type_cd", length = 20)
  private String batteryTypeCode;

  @Column(name = "rx_code_cd", length = 10)
  private String rxCode;

  @Column(name = "condition_code_cd", length = 20)
  private String conditionCode;

  @Column(name = "is_auto_generated", nullable = false)
  private boolean autoGenerated;

  @Column(name = "created_at", nullable = false)
  private Instant createdAt;

  /** 사유가 appearance일 때만 붙어야 하는데 다중 테이블 조건이라 CHECK로 못 건다 — 서비스 계층이 유일한 방어선이다. */
  @ElementCollection(fetch = FetchType.LAZY)
  @CollectionTable(
      name = "replacement_item_flags",
      joinColumns = @JoinColumn(name = "replacement_item_id"))
  @Column(name = "detector_flag_cd", length = 20, nullable = false)
  private Set<String> detectorFlagCodes = new LinkedHashSet<>();

  protected ReplacementItem() {}

  public ReplacementItem(
      short itemSeq,
      String replaceReasonCode,
      String batteryTypeCode,
      String rxCode,
      String conditionCode,
      boolean autoGenerated) {
    this.itemSeq = itemSeq;
    this.replaceReasonCode = replaceReasonCode;
    this.batteryTypeCode = batteryTypeCode;
    this.rxCode = rxCode;
    this.conditionCode = conditionCode;
    this.autoGenerated = autoGenerated;
  }

  /** Visit.addReplacementItem에서만 호출한다. */
  void assignTo(Visit visit) {
    this.visit = visit;
  }

  public void addFlag(String detectorFlagCode) {
    this.detectorFlagCodes.add(detectorFlagCode);
  }

  @PrePersist
  void onCreate() {
    this.createdAt = Instant.now();
  }

  public Long getId() {
    return id;
  }

  public Visit getVisit() {
    return visit;
  }

  public short getItemSeq() {
    return itemSeq;
  }

  public String getReplaceReasonCode() {
    return replaceReasonCode;
  }

  public String getBatteryTypeCode() {
    return batteryTypeCode;
  }

  public String getRxCode() {
    return rxCode;
  }

  public String getConditionCode() {
    return conditionCode;
  }

  public boolean isAutoGenerated() {
    return autoGenerated;
  }

  public Instant getCreatedAt() {
    return createdAt;
  }

  public Set<String> getDetectorFlagCodes() {
    return detectorFlagCodes;
  }
}
