package com.daullim.backend.domain.visit.service;

import java.util.Set;

/** 교체 항목 1건의 판정 결과. */
public record ItemJudgment(
    short itemSeq,
    String replaceReasonCode,
    String batteryTypeCode,
    Set<String> detectorFlagCodes,
    String rxCode,
    String conditionCode,
    boolean autoGenerated) {}
