package com.daullim.backend.domain.visit.service;

import com.daullim.backend.common.error.BusinessException;
import com.daullim.backend.common.error.ErrorCode;
import com.daullim.backend.domain.code.service.CodeBook;
import com.daullim.backend.domain.code.service.CodeBookProvider;
import com.daullim.backend.domain.unit.entity.Unit;
import com.daullim.backend.domain.unit.repository.UnitRepository;
import com.daullim.backend.domain.user.entity.User;
import com.daullim.backend.domain.user.repository.UserRepository;
import com.daullim.backend.domain.visit.entity.ReplacementItem;
import com.daullim.backend.domain.visit.entity.Visit;
import com.daullim.backend.domain.visit.repository.VisitRepository;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.Optional;
import org.springframework.stereotype.Service;
import org.springframework.transaction.annotation.Transactional;

/**
 * 점검 1건 저장 — 방문·교체 항목·외관 플래그·세대 캐시를 한 트랜잭션에서 처리.
 */
@Service
public class VisitSubmissionService {

  private static final DateTimeFormatter DAY = DateTimeFormatter.BASIC_ISO_DATE;

  private final JudgmentService judgment;
  private final CodeBookProvider codeBooks;
  private final VisitRepository visits;
  private final UnitRepository units;
  private final UserRepository users;
  private final Clock clock;

  VisitSubmissionService(
      JudgmentService judgment,
      CodeBookProvider codeBooks,
      VisitRepository visits,
      UnitRepository units,
      UserRepository users,
      Clock clock) {
    this.judgment = judgment;
    this.codeBooks = codeBooks;
    this.visits = visits;
    this.units = units;
    this.users = users;
    this.clock = clock;
  }

  @Transactional
  public VisitSaveResult submit(VisitSubmission raw) {
    VisitSubmission s = raw.normalized();
    CodeBook cb = codeBooks.get();

    // 현장은 오프라인에서 재전송한다. 같은 키가 이미 있으면 다시 저장하지 않는다.
    Optional<Visit> replay = findReplay(s);
    if (replay.isPresent()) {
      Visit saved = replay.get();
      return new VisitSaveResult(saved.getId(), saved.getVisitedDay(), true);
    }

    // 세대 캐시는 이 트랜잭션과 야간 재산입 스캔 둘이 쓴다 — 갱신 전에 잠근다.
    Unit unit =
        units
            .findByIdForUpdate(s.unitId())
            .orElseThrow(() -> notFound("세대를 찾을 수 없습니다: unitId=" + s.unitId()));
    User officer =
        users
            .findById(s.officerId())
            .orElseThrow(() -> notFound("점검원을 찾을 수 없습니다: officerId=" + s.officerId()));

    AlarmJudgment j = judgment.judge(s);
    String visitedDay = LocalDate.now(clock).format(DAY);
    // 점검을 못 한 방문에 현장 교체가 있을 수 없다.
    String rxDone = j.inspected() ? s.rxDoneCode() : null;

    Visit visit = assemble(s, j, unit, officer, visitedDay, rxDone);
    visits.save(visit);

    unit.recordVisit(cb.consentStatus(s.consentCode()).getUnitStatusCode(), visitedDay);
    rxBaselineDay(s, visitedDay, rxDone).ifPresent(unit::markRxBaseline);

    return new VisitSaveResult(visit.getId(), visitedDay, false);
  }

  private Optional<Visit> findReplay(VisitSubmission s) {
    return s.clientVisitId() == null
        ? Optional.empty()
        : visits.findByClientVisitId(s.clientVisitId());
  }

  private Visit assemble(
      VisitSubmission s,
      AlarmJudgment j,
      Unit unit,
      User officer,
      String visitedDay,
      String rxDone) {
    Visit visit =
        new Visit(
            unit,
            officer,
            visitedDay,
            Instant.now(clock),
            s.consentCode(),
            j.inspected(),
            j.ruleVersion());

    visit.applyGate(
        s.respondentTypeCode(),
        s.refusalReasonCode(),
        s.selfReportPeriodCode(),
        s.selfReportTestedCode(),
        s.refusalNote());

    visit.applyAlarmJudgment(
        j.roomCount(),
        j.mfgYm(),
        j.ageBandCode(),
        j.replaceCount(),
        j.expired(),
        j.effectiveReplaceCount(),
        j.conditionCode());

    // 점검을 못 한 방문은 소화기가 발생 자체를 하지 않는다 (ck_v_na).
    visit.applyPostCare(
        j.inspected() ? s.extinguisherInstalledCode() : null,
        rxDone,
        s.revisitPlanCode(),
        s.note());

    visit.applyDispatchSnapshot(
        s.clientVisitId(),
        s.routeOrder(),
        s.dispatchedScore(),
        s.dispatchedOrderKey(),
        s.scoreVersion(),
        s.gpsLat(),
        s.gpsLng());

    for (ItemJudgment item : j.items()) {
      ReplacementItem row =
          new ReplacementItem(
              item.itemSeq(),
              item.replaceReasonCode(),
              item.batteryTypeCode(),
              item.rxCode(),
              item.conditionCode(),
              item.autoGenerated());
      item.detectorFlagCodes().forEach(row::addFlag);
      visit.addReplacementItem(row);
    }
    return visit;
  }

  /**
   * 재산입 기준일 — 여기서 15년이 지나면 세대가 다시 큐로 온다.
   */
  private Optional<String> rxBaselineDay(VisitSubmission s, String visitedDay, String rxDone) {
    if ("done".equals(rxDone)) {
      return Optional.of(visitedDay);
    }
    if ("self-replaced".equals(s.refusalReasonCode())) {
      return Optional.of(backdated(visitedDay, s.selfReportPeriodCode()));
    }
    return Optional.empty();
  }

  /** 자가신고는 주민 진술만큼 소급한다. 다만 '모름'은 소급할 근거가 없으므로 지어내지 않는다. */
  private String backdated(String visitedDay, String selfReportPeriodCode) {
    LocalDate day = LocalDate.parse(visitedDay, DAY);
    LocalDate baseline =
        switch (selfReportPeriodCode == null ? "" : selfReportPeriodCode) {
          case "within-6m" -> day.minusMonths(6);
          // 'over-1y'는 정확한 시점을 모르므로 알 수 있는 하한인 1년만 소급한다.
          case "within-1y", "over-1y" -> day.minusYears(1);
          default -> day;
        };
    return baseline.format(DAY);
  }

  private static BusinessException notFound(String message) {
    return new BusinessException(ErrorCode.NOT_FOUND, message);
  }
}
