package com.daullim.backend.domain.visit.dto;

import java.util.List;

/**
 * 교체 대상 1건의 저장 결과 — 현장 원입력과 서버 판정이 함께 있다.
 *
 * <p>{@code autoGenerated}가 참이면 점검원이 항목별로 고른 것이 아니라 전량 교체 확정(경과·미표기)으로 서버가 실 개수만큼 만든 행이다.
 */
public record ReplacementItemResponse(
    short itemSeq,
    String replaceReasonCd,
    String batteryTypeCd,
    String rxCodeCd,
    String conditionCode,
    boolean autoGenerated,
    List<String> detectorFlagCds) {}
