package com.daullim.backend.domain.visit.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.daullim.backend.TestcontainersConfiguration;
import com.daullim.backend.common.error.BusinessException;
import com.daullim.backend.common.error.ErrorCode;
import com.daullim.backend.domain.code.service.CodeBookProvider;
import java.time.Clock;
import java.time.Instant;
import java.time.ZoneId;
import java.util.List;
import java.util.Set;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.context.annotation.Import;

/** 판정 규칙 고정 — lookup은 실제 seed 사용(엔티티에 public 생성자 없음), 시계는 테스트마다 고정. */
@Import(TestcontainersConfiguration.class)
@SpringBootTest
class JudgmentServiceTest {

  private static final ZoneId KST = ZoneId.of("Asia/Seoul");

  @Autowired CodeBookProvider codeBooks;

  /** 지정 시각 고정 판정 서비스. */
  private JudgmentService on(String instant) {
    return new JudgmentService(codeBooks, Clock.fixed(Instant.parse(instant), KST));
  }

  /* ------------------------------ 내용연수 ------------------------------ */

  @Test
  @DisplayName("제조 15년째 되는 달에 경과로 넘어간다")
  void expiryBoundary() {
    VisitSubmission fifteenYearsOld = accepted(3, "2011-07", 0, List.of());

    assertThat(on("2026-07-15T00:00:00Z").judge(fifteenYearsOld).expired()).isTrue();
    assertThat(on("2026-06-15T00:00:00Z").judge(fifteenYearsOld).expired()).isFalse();
  }

  @Test
  @DisplayName("경과면 작동 여부와 무관하게 실 개수만큼 전량 교체가 된다")
  void expiredReplacesEveryRoom() {
    AlarmJudgment j = on("2026-07-15T00:00:00Z").judge(accepted(3, "2005-01", null, List.of()));

    assertThat(j.expired()).isTrue();
    assertThat(j.effectiveReplaceCount()).isEqualTo((short) 3);
    assertThat(j.conditionCode()).isEqualTo("EXPIRED");
    assertThat(j.items()).hasSize(3);
    assertThat(j.items())
        .allSatisfy(
            item -> {
              assertThat(item.replaceReasonCode()).isEqualTo("expired");
              assertThat(item.autoGenerated()).isTrue();
              assertThat(item.rxCode()).isEqualTo("RX-IOT");
            });
    assertThat(j.items())
        .extracting(ItemJudgment::itemSeq)
        .containsExactly((short) 1, (short) 2, (short) 3);
  }

  @Test
  @DisplayName("미래 제조년월은 거부한다")
  void futureManufactureDateIsRejected() {
    assertThatThrownBy(() -> on("2026-07-15T00:00:00Z").judge(accepted(1, "2027-01", 0, List.of())))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("미래");
  }

  /* -------------------------------- 처방 -------------------------------- */

  @Test
  @DisplayName("일체형 방전은 전지 교체가 불가해 기기 교체로 뒤집힌다")
  void sealedBatteryFlipsPrescription() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(battery("sealed"))));

    assertThat(j.items()).singleElement().extracting(ItemJudgment::rxCode).isEqualTo("RX-IOT");
  }

  @Test
  @DisplayName("교체형 방전은 전지 교체다")
  void replaceableBatteryKeepsPrescription() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z")
            .judge(accepted(2, "2020-01", 1, List.of(battery("replaceable"))));

    assertThat(j.items()).singleElement().extracting(ItemJudgment::rxCode).isEqualTo("RX-BAT");
  }

  @Test
  @DisplayName("전지 유형 '모름'은 판별 전이라 사유 기준값으로 폴백한다")
  void unknownBatteryFallsBackToReasonPrescription() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(battery("unknown"))));

    assertThat(j.items()).singleElement().extracting(ItemJudgment::rxCode).isEqualTo("RX-BAT");
  }

  /* -------------------------------- 판정 -------------------------------- */

  @Test
  @DisplayName("커버 파손은 중대결함이라 외관이상이어도 불량이다")
  void severeFlagMakesItDefective() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z")
            .judge(accepted(2, "2020-01", 1, List.of(appearance("cover-damage"))));

    assertThat(j.conditionCode()).isEqualTo("DEFECTIVE");
  }

  @Test
  @DisplayName("오염만 있으면 교체권고에 그친다")
  void nonSevereFlagIsAdvisoryOnly() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(appearance("stain"))));

    assertThat(j.conditionCode()).isEqualTo("REPLACE_ADVISED");
  }

  @Test
  @DisplayName("제조년월 미표기는 연차를 논할 자격이 없어 경과가 아니라 불량이다")
  void unmarkedIsDefectiveNotExpired() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(reason("unmarked"))));

    assertThat(j.expired()).isFalse();
    assertThat(j.conditionCode()).isEqualTo("DEFECTIVE");
  }

  @Test
  @DisplayName("여러 항목이면 가장 나쁜 판정이 세대 판정이 된다")
  void overallIsTheWorstItem() {
    AlarmJudgment j =
        on("2026-07-15T00:00:00Z")
            .judge(
                accepted(
                    3, "2020-01", 2, List.of(appearance("stain"), appearance("cover-damage"))));

    assertThat(j.items())
        .extracting(ItemJudgment::conditionCode)
        .containsExactly("REPLACE_ADVISED", "DEFECTIVE");
    assertThat(j.conditionCode()).isEqualTo("DEFECTIVE");
  }

  @Test
  @DisplayName("교체 0건이면 양호다")
  void noReplacementIsGood() {
    AlarmJudgment j = on("2026-07-15T00:00:00Z").judge(accepted(3, "2022-05", 0, List.of()));

    assertThat(j.conditionCode()).isEqualTo("OK_GOOD");
    assertThat(j.items()).isEmpty();
    assertThat(j.effectiveReplaceCount()).isEqualTo((short) 0);
  }

  /* ------------------------------ 비승낙 ------------------------------ */

  @Test
  @DisplayName("비승낙 방문은 경보기 필드가 전량 비어 있다")
  void notInspectedLeavesAlarmFieldsNull() {
    for (String consent : new String[] {"refused", "vacant", "unreachable"}) {
      AlarmJudgment j = on("2026-07-15T00:00:00Z").judge(gate(consent));

      assertThat(j.inspected()).isFalse();
      assertThat(j.roomCount()).isNull();
      assertThat(j.expired()).isNull();
      assertThat(j.effectiveReplaceCount()).isNull();
      assertThat(j.conditionCode()).isNull();
      assertThat(j.items()).isEmpty();
    }
  }

  @Test
  @DisplayName("제조년월 미표기는 경과가 아니라 불량이고, 실 전량이 교체 대상이 된다")
  void unmarkedIsDefectiveAndReplacesAll() {
    AlarmJudgment j = on("2026-07-15T00:00:00Z").judge(accepted(3, null, true, null, List.of()));

    assertThat(j.mfgUnmarked()).isTrue();
    assertThat(j.expired()).isFalse();
    assertThat(j.conditionCode()).isEqualTo("DEFECTIVE");
    assertThat(j.effectiveReplaceCount()).isEqualTo((short) 3);
    assertThat(j.items()).hasSize(3);
    assertThat(j.items())
        .allSatisfy(
            item -> {
              assertThat(item.replaceReasonCode()).isEqualTo("unmarked");
              assertThat(item.conditionCode()).isEqualTo("DEFECTIVE");
              assertThat(item.rxCode()).isEqualTo("RX-IOT");
              assertThat(item.autoGenerated()).isTrue();
            });
  }

  @Test
  @DisplayName("실측이 있으면 미표기 플래그가 함께 와도 정규화가 지운다")
  void measuredMfgYmWinsOverUnmarked() {
    AlarmJudgment j = on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", true, 0, List.of()));

    assertThat(j.mfgUnmarked()).isFalse();
    assertThat(j.conditionCode()).isEqualTo("OK_GOOD");
  }

  @Test
  @DisplayName("제조년월도 미표기도 없으면 입력 오류다")
  void missingMfgEvidenceIsRejected() {
    assertThatThrownBy(
            () -> on("2026-07-15T00:00:00Z").judge(accepted(2, null, false, 0, List.of())))
        .hasMessageContaining("mfgYm");
  }

  @Test
  @DisplayName("재방문 필요 여부가 비면 승낙·비승낙 가리지 않고 입력 오류다")
  void revisitPlanIsRequired() {
    assertThatThrownBy(() -> on("2026-07-15T00:00:00Z").judge(withRevisit(gate("vacant"), null)))
        .hasMessageContaining("revisitPlanCode");
  }

  @Test
  @DisplayName("경과인데 교체도 재방문도 없으면 사유가 있어야 한다")
  void expiredWithoutActionRequiresReason() {
    VisitSubmission dropped =
        withPostCare(accepted(2, "2005-01", null, List.of()), "advised-only", "not-needed", null);
    assertThatThrownBy(() -> on("2026-07-15T00:00:00Z").judge(dropped))
        .hasMessageContaining("noRevisitNote");

    VisitSubmission justified =
        withPostCare(
            accepted(2, "2005-01", null, List.of()),
            "advised-only",
            "not-needed",
            "소유자가 자비로 교체 예정");
    assertThat(on("2026-07-15T00:00:00Z").judge(justified).conditionCode()).isEqualTo("EXPIRED");
  }

  @Test
  @DisplayName("미표기도 교체·재방문 없이 끝내려면 사유가 필요.")
  void unmarkedWithoutActionRequiresReason() {
    VisitSubmission dropped =
        withPostCare(accepted(2, null, true, null, List.of()), "advised-only", "not-needed", null);
    assertThatThrownBy(() -> on("2026-07-15T00:00:00Z").judge(dropped))
        .hasMessageContaining("noRevisitNote");

    VisitSubmission justified =
        withPostCare(
            accepted(2, null, true, null, List.of()),
            "advised-only",
            "not-needed",
            "다음 분기 일괄 교체 대상");
    assertThat(on("2026-07-15T00:00:00Z").judge(justified).conditionCode()).isEqualTo("DEFECTIVE");
  }

  @Test
  @DisplayName("경과라도 현장에서 교체를 끝냈으면 사유를 묻지 않는다")
  void expiredWithReplacementNeedsNoReason() {
    VisitSubmission done =
        withPostCare(accepted(2, "2005-01", null, List.of()), "done", "not-needed", null);
    assertThat(on("2026-07-15T00:00:00Z").judge(done).expired()).isTrue();
  }

  @Test
  @DisplayName("승낙으로 바꿔 놓고 거부 사유가 남아 오면 조용히 지운다")
  void staleGateFieldsAreNormalizedAway() {
    VisitSubmission stale =
        new VisitSubmission(
            1L,
            1L,
            null,
            "accepted",
            "owner",
            "no-time",
            "잔존 메모",
            2,
            "2022-01",
            false,
            0,
            List.of(),
            "installed",
            null,
            "not-needed",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null);

    assertThat(stale.normalized().refusalReasonCode()).isNull();
    assertThat(stale.normalized().refusalNote()).isNull();
    // 정규화 없이 그대로 내려갔다면 DB의 ck_v_gate1에 걸렸을 입력이다.
    assertThat(on("2026-07-15T00:00:00Z").judge(stale).conditionCode()).isEqualTo("OK_GOOD");
  }

  /* ------------------------------- 거부 ------------------------------- */

  @Test
  @DisplayName("사유 없는 교체 항목은 입력 오류로 잡는다")
  void itemWithoutReasonIsValidationError() {
    assertThatThrownBy(
            () ->
                on("2026-07-15T00:00:00Z")
                    .judge(
                        accepted(2, "2020-01", 1, List.of(new ReplacementInput(null, null, null)))))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("replacements[0].replaceReasonCode")
        .extracting(e -> ((BusinessException) e).getErrorCode())
        .isEqualTo(ErrorCode.VALIDATION_ERROR);
  }

  @Test
  @DisplayName("교체 개수와 사유 항목 수가 다르면 입력 오류다")
  void countMismatchIsValidationError() {
    assertThatThrownBy(
            () ->
                on("2026-07-15T00:00:00Z").judge(accepted(3, "2020-01", 2, List.of(reason("etc")))))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("교체 개수");
  }

  @Test
  @DisplayName("외관이상이 아닌데 세부 항목이 붙으면 거부한다 — DB가 막아주지 않는 유일한 규칙")
  void flagsOnNonAppearanceReasonAreRejected() {
    ReplacementInput bad = new ReplacementInput("detached", null, Set.of("stain"));

    assertThatThrownBy(
            () -> on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(bad))))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("detectorFlagCodes");
  }

  @Test
  @DisplayName("방전이 아닌데 전지 유형이 붙으면 거부한다")
  void batteryTypeOnNonBatteryReasonIsRejected() {
    ReplacementInput bad = new ReplacementInput("detached", "sealed", null);

    assertThatThrownBy(
            () -> on("2026-07-15T00:00:00Z").judge(accepted(2, "2020-01", 1, List.of(bad))))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("batteryTypeCode");
  }

  @Test
  @DisplayName("서버가 모르는 코드값은 seed 드리프트 신호로 따로 뺀다")
  void unknownCodeIsDomainCodeInvalid() {
    assertThatThrownBy(
            () ->
                on("2026-07-15T00:00:00Z")
                    .judge(accepted(2, "2020-01", 1, List.of(reason("no-such-reason")))))
        .isInstanceOf(BusinessException.class)
        .extracting(e -> ((BusinessException) e).getErrorCode())
        .isEqualTo(ErrorCode.DOMAIN_CODE_INVALID);
  }

  @Test
  @DisplayName("승낙인데 응대자·소화기가 비면 입력 오류다")
  void acceptedRequiresRespondentAndExtinguisher() {
    VisitSubmission noRespondent =
        new VisitSubmission(
            1L,
            1L,
            null,
            "accepted",
            null,
            null,
            null,
            2,
            "2022-01",
            false,
            0,
            List.of(),
            "installed",
            null,
            "not-needed",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null);

    assertThatThrownBy(() -> on("2026-07-15T00:00:00Z").judge(noRespondent))
        .hasMessageContaining("respondentTypeCode");
  }

  /* ------------------------------ 픽스처 ------------------------------ */

  private static VisitSubmission accepted(
      int roomCount, String mfgYm, Integer replaceCount, List<ReplacementInput> items) {
    return accepted(roomCount, mfgYm, false, replaceCount, items);
  }

  private static VisitSubmission accepted(
      int roomCount,
      String mfgYm,
      boolean mfgUnmarked,
      Integer replaceCount,
      List<ReplacementInput> items) {
    return new VisitSubmission(
        1L,
        1L,
        null,
        "accepted",
        "owner",
        null,
        null,
        roomCount,
        mfgYm,
        mfgUnmarked,
        replaceCount,
        items,
        "installed",
        null,
        // 재방문 필요는 ③ 규칙을 건드리지 않는다 — 판정만 보는 픽스처의 중립값
        "revisit",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
  }

  private static VisitSubmission gate(String consentCode) {
    String refusalReason = "refused".equals(consentCode) ? "no-time" : null;
    return new VisitSubmission(
        1L,
        1L,
        null,
        consentCode,
        null,
        refusalReason,
        null,
        null,
        null,
        false,
        null,
        List.of(),
        null,
        null,
        "not-needed",
        null,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
  }

  private static VisitSubmission withRevisit(VisitSubmission s, String revisitPlanCode) {
    return withPostCare(s, s.rxDoneCode(), revisitPlanCode, s.noRevisitNote());
  }

  private static VisitSubmission withPostCare(
      VisitSubmission s, String rxDoneCode, String revisitPlanCode, String noRevisitNote) {
    return new VisitSubmission(
        s.unitId(),
        s.officerId(),
        s.clientVisitId(),
        s.consentCode(),
        s.respondentTypeCode(),
        s.refusalReasonCode(),
        s.refusalNote(),
        s.roomCount(),
        s.mfgYm(),
        s.mfgUnmarked(),
        s.replaceCount(),
        s.replacements(),
        s.extinguisherInstalledCode(),
        rxDoneCode,
        revisitPlanCode,
        noRevisitNote,
        s.note(),
        s.routeOrder(),
        s.dispatchedScore(),
        s.dispatchedOrderKey(),
        s.scoreVersion(),
        s.gpsLat(),
        s.gpsLng());
  }

  private static ReplacementInput reason(String code) {
    return new ReplacementInput(code, null, null);
  }

  private static ReplacementInput battery(String batteryTypeCode) {
    return new ReplacementInput("battery-dead", batteryTypeCode, null);
  }

  private static ReplacementInput appearance(String flag) {
    return new ReplacementInput("appearance", null, Set.of(flag));
  }
}
