package com.daullim.backend.domain.visit.service;

import static org.assertj.core.api.Assertions.assertThat;
import static org.assertj.core.api.Assertions.assertThatThrownBy;

import com.daullim.backend.TestcontainersConfiguration;
import com.daullim.backend.common.error.BusinessException;
import com.daullim.backend.domain.building.repository.BuildingRepository;
import com.daullim.backend.domain.unit.entity.Unit;
import com.daullim.backend.domain.unit.repository.UnitRepository;
import com.daullim.backend.domain.user.entity.User;
import com.daullim.backend.domain.user.repository.UserRepository;
import com.daullim.backend.domain.visit.entity.ReplacementItem;
import com.daullim.backend.domain.visit.entity.Visit;
import com.daullim.backend.domain.visit.repository.VisitRepository;
import jakarta.persistence.EntityManager;
import java.time.Clock;
import java.time.Instant;
import java.time.LocalDate;
import java.time.ZoneId;
import java.util.List;
import java.util.Set;
import java.util.UUID;
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.DisplayName;
import org.junit.jupiter.api.Test;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.test.context.SpringBootTest;
import org.springframework.boot.test.context.TestConfiguration;
import org.springframework.context.annotation.Bean;
import org.springframework.context.annotation.Import;
import org.springframework.context.annotation.Primary;
import org.springframework.jdbc.core.simple.JdbcClient;
import org.springframework.transaction.annotation.Transactional;

/** 저장 경계 검증 — 방문·교체 항목·외관 플래그·세대 캐시·재산입 기준일의 단일 트랜잭션 처리. */
@Import({TestcontainersConfiguration.class, VisitSubmissionIT.FixedClock.class})
@SpringBootTest
@Transactional
class VisitSubmissionIT {

  /** 오늘 고정 */
  @TestConfiguration
  static class FixedClock {
    @Bean
    @Primary
    Clock fixedClock() {
      return Clock.fixed(Instant.parse("2026-07-15T00:00:00Z"), ZoneId.of("Asia/Seoul"));
    }
  }

  private static final String TODAY = "20260715";

  @Autowired VisitSubmissionService service;
  @Autowired VisitRepository visits;
  @Autowired UnitRepository units;
  @Autowired UserRepository users;
  @Autowired BuildingRepository buildings;
  @Autowired JdbcClient jdbc;
  @Autowired EntityManager em;

  private Long unitId;
  private Long officerId;

  @BeforeEach
  void setUp() {
    String bldKey = "TEST-" + UUID.randomUUID();
    jdbc.sql(
            """
            INSERT INTO buildings (bld_key,sido_cd,sigungu_cd,admin_dong_cd,address,lat,lng,
              house_type_cd,floor_count,unit_count,region_type_cd,score,risk_level_cd,
              order_key,score_version,computed_at)
            VALUES (:k,'11','11620','1162053','서울 관악구 신림동 1',37.4,126.9,
              'multi-family',3,4,'URBAN',88.5,'danger',1,'v1',now())
            """)
        .param("k", bldKey)
        .update();

    officerId =
        users
            .save(
                new User(
                    "kim-" + UUID.randomUUID(),
                    "{bcrypt}stub",
                    "김점검",
                    "010-1234-5678",
                    LocalDate.of(1990, 1, 1),
                    "officer"))
            .getId();
    unitId =
        units
            .save(
                new Unit(
                    buildings.findByBldKey(bldKey).orElseThrow(),
                    (short) 1,
                    "101호",
                    (short) 1,
                    "expos",
                    "pending"))
            .getId();
  }

  @Test
  @DisplayName("내용연수 경과 방문: 방문·자동 생성 항목·세대 캐시가 한 번에 저장된다")
  void expiredVisitSavesEverything() {
    VisitSaveResult result = service.submit(accepted(3, "2005-01", null, List.of(), "done"));
    em.flush();
    em.clear();

    assertThat(result.replay()).isFalse();
    assertThat(result.visitedDay()).isEqualTo(TODAY);

    Visit saved = visits.findById(result.visitId()).orElseThrow();
    assertThat(saved.isInspected()).isTrue();
    assertThat(saved.getExpired()).isTrue();
    assertThat(saved.getEffectiveReplaceCount()).isEqualTo((short) 3);
    assertThat(saved.getConditionCode()).isEqualTo("EXPIRED");
    assertThat(saved.getRuleVersion()).isEqualTo("v1");
    assertThat(saved.isMfgUnmarked()).isFalse();

    assertThat(saved.getReplacementItems()).hasSize(3);
    assertThat(saved.getReplacementItems())
        .allSatisfy(
            item -> {
              assertThat(item.getReplaceReasonCode()).isEqualTo("expired");
              assertThat(item.isAutoGenerated()).isTrue();
              assertThat(item.getRxCode()).isEqualTo("RX-IOT");
            });

    Unit unit = units.findById(unitId).orElseThrow();
    assertThat(unit.getStatusCode()).isEqualTo("done");
    assertThat(unit.getLastInspectedDay()).isEqualTo(TODAY);
    assertThat(unit.getRxBaselineDay()).isEqualTo(TODAY);
  }

  @Test
  @DisplayName("외관 세부 항목이 플래그 테이블까지 함께 들어간다")
  void appearanceFlagsCascade() {
    VisitSaveResult result =
        service.submit(
            accepted(
                2,
                "2020-01",
                1,
                List.of(new ReplacementInput("appearance", null, Set.of("cover-damage", "stain"))),
                "advised-only"));
    em.flush();
    em.clear();

    Visit saved = visits.findById(result.visitId()).orElseThrow();
    assertThat(saved.getConditionCode()).isEqualTo("DEFECTIVE");
    assertThat(saved.getReplacementItems())
        .singleElement()
        .extracting(ReplacementItem::getDetectorFlagCodes)
        .satisfies(f -> assertThat(f).containsExactlyInAnyOrder("cover-damage", "stain"));

    Integer flagRows =
        jdbc.sql("SELECT count(*) FROM replacement_item_flags").query(Integer.class).single();
    assertThat(flagRows).isEqualTo(2);
  }

  @Test
  @DisplayName("제조년월 미표기 방문이 실측 없이 저장된다")
  void unmarkedVisitSaves() {
    VisitSaveResult result = service.submit(accepted(2, null, true, null, List.of(), "done"));
    em.flush();
    em.clear();

    Visit saved = visits.findById(result.visitId()).orElseThrow();
    assertThat(saved.getMfgYm()).isNull();
    assertThat(saved.isMfgUnmarked()).isTrue();
    assertThat(saved.getExpired()).isFalse();
    assertThat(saved.getConditionCode()).isEqualTo("DEFECTIVE");
    assertThat(saved.getEffectiveReplaceCount()).isEqualTo((short) 2);
    assertThat(saved.getReplacementItems())
        .hasSize(2)
        .allSatisfy(item -> assertThat(item.getReplaceReasonCode()).isEqualTo("unmarked"));
  }

  @Test
  @DisplayName("교체가 없었으면 기준일이 방문일이 아니라 제조년월로 찍힌다")
  void noReplacementKeepsManufacturedClock() {
    service.submit(accepted(2, "2020-01", 0, List.of(), "advised-only"));
    em.flush();
    em.clear();

    // 권고만 받고 끝난 세대도 남은 기간 뒤에는 제 발로 큐에 돌아와야 한다
    assertThat(units.findById(unitId).orElseThrow().getRxBaselineDay()).isEqualTo("20200101");
  }

  @Test
  @DisplayName("미표기 세대도 사유 없이는 종료할 수 없고, 사유가 있으면 기준일 없이 큐에서 빠진다")
  void unmarkedWithoutActionNeedsReason() {
    assertThatThrownBy(
            () ->
                service.submit(
                    accepted(2, null, true, null, List.of(), "advised-only", "not-needed", null)))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("noRevisitNote");

    service.submit(
        accepted(2, null, true, null, List.of(), "advised-only", "not-needed", "다음 분기 일괄 교체 대상"));
    em.flush();
    em.clear();

    Unit unit = units.findById(unitId).orElseThrow();
    assertThat(unit.getStatusCode()).isEqualTo("done");
    assertThat(unit.getRxBaselineDay()).isNull();
  }

  @Test
  @DisplayName("경과 세대를 사유와 함께 종료하면 예전 기준일까지 지워 다시 올라오지 않는다")
  void expiredWithReasonClearsStaleBaseline() {
    Unit unit = units.findById(unitId).orElseThrow();
    unit.markRxBaseline("20050101");
    em.flush();

    service.submit(
        accepted(
            2, "2005-01", false, null, List.of(), "advised-only", "not-needed", "소유자가 자비로 교체 예정"));
    em.flush();
    em.clear();

    assertThat(units.findById(unitId).orElseThrow().getRxBaselineDay()).isNull();
  }

  @Test
  @DisplayName("점검을 못 한 방문은 기존 기준일을 건드리지 않는다")
  void notInspectedVisitKeepsBaseline() {
    units.findById(unitId).orElseThrow().markRxBaseline("20200101");
    em.flush();

    service.submit(
        new VisitSubmission(
            unitId,
            officerId,
            null,
            "vacant",
            null,
            null,
            null,
            null,
            null,
            false,
            null,
            List.of(),
            null,
            null,
            "not-needed",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null));
    em.flush();
    em.clear();

    assertThat(units.findById(unitId).orElseThrow().getRxBaselineDay()).isEqualTo("20200101");
  }

  @Test
  @DisplayName("비승낙 방문은 경보기·소화기가 전량 비고, 재방문이 필요하면 세대가 큐에 남는다")
  void notInspectedVisitLeavesAlarmFieldsNull() {
    VisitSubmission vacant =
        new VisitSubmission(
            unitId,
            officerId,
            null,
            "vacant",
            null,
            null,
            null,
            null,
            null,
            false,
            null,
            List.of(),
            // 클라이언트가 실수로 실어 보내도 저장되지 않아야 한다
            "installed",
            "done",
            "revisit",
            null,
            "부재",
            null,
            null,
            null,
            null,
            null,
            null);

    VisitSaveResult result = service.submit(vacant);
    em.flush();
    em.clear();

    Visit saved = visits.findById(result.visitId()).orElseThrow();
    assertThat(saved.isInspected()).isFalse();
    assertThat(saved.getExtinguisherInstalledCode()).isNull();
    assertThat(saved.getRxDoneCode()).isNull();
    assertThat(saved.getConditionCode()).isNull();
    // 점검을 못 한 방문의 rxDone='done'은 버려지므로 재방문 판단을 뒤집지 못한다
    assertThat(saved.getRevisitPlanCode()).isEqualTo("revisit");

    Unit unit = units.findById(unitId).orElseThrow();
    assertThat(unit.getStatusCode()).isEqualTo("pending");
    assertThat(unit.getRxBaselineDay()).isNull();
  }

  @Test
  @DisplayName("비승낙이라도 재방문이 필요 없으면 세대가 거부로 내려간다")
  void notInspectedWithoutRevisitLeavesQueue() {
    service.submit(
        new VisitSubmission(
            unitId,
            officerId,
            null,
            "vacant",
            null,
            null,
            null,
            null,
            null,
            false,
            null,
            List.of(),
            null,
            null,
            "not-needed",
            null,
            "장기 공가",
            null,
            null,
            null,
            null,
            null,
            null));
    em.flush();
    em.clear();

    assertThat(units.findById(unitId).orElseThrow().getStatusCode()).isEqualTo("refused");
  }

  @Test
  @DisplayName("승낙 + 현장 교체 완료면 재방문 여부를 물어도 불필요로 고정된다")
  void rxDoneForcesNoRevisit() {
    VisitSaveResult result =
        service.submit(accepted(2, "2020-01", false, 0, List.of(), "done", "revisit", null));
    em.flush();
    em.clear();

    assertThat(visits.findById(result.visitId()).orElseThrow().getRevisitPlanCode())
        .isEqualTo("not-needed");
    Unit unit = units.findById(unitId).orElseThrow();
    assertThat(unit.getStatusCode()).isEqualTo("done");
    assertThat(unit.getRxBaselineDay()).isEqualTo(TODAY);
  }

  @Test
  @DisplayName("경과 세대를 교체·재방문 없이 종료하려면 사유가 있어야 하고, 있으면 큐에서 빠진다")
  void expiredWithoutActionNeedsReason() {
    assertThatThrownBy(
            () ->
                service.submit(
                    accepted(
                        2, "2005-01", false, null, List.of(), "advised-only", "not-needed", null)))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("noRevisitNote");

    service.submit(
        accepted(
            2, "2005-01", false, null, List.of(), "advised-only", "not-needed", "소유자가 자비로 교체 예정"));
    em.flush();
    em.clear();

    Unit unit = units.findById(unitId).orElseThrow();
    assertThat(unit.getStatusCode()).isEqualTo("done");
    assertThat(unit.getRxBaselineDay()).isNull();
  }

  @Test
  @DisplayName("같은 멱등 키로 다시 보내면 새로 저장하지 않고 기존 건을 돌려준다")
  void resubmitWithSameKeyIsReplay() {
    UUID key = UUID.randomUUID();
    VisitSubmission first = withKey(accepted(2, "2020-01", 0, List.of(), "advised-only"), key);

    VisitSaveResult saved = service.submit(first);
    em.flush();
    VisitSaveResult again = service.submit(first);
    em.flush();

    assertThat(again.replay()).isTrue();
    assertThat(again.visitId()).isEqualTo(saved.visitId());
    assertThat(visits.findByUnitIdAndDeletedAtIsNullOrderByVisitedAtDesc(unitId)).hasSize(1);
  }

  @Test
  @DisplayName("없는 세대로 저장하면 404다")
  void unknownUnitIsNotFound() {
    VisitSubmission orphan =
        new VisitSubmission(
            -1L,
            officerId,
            null,
            "vacant",
            null,
            null,
            null,
            null,
            null,
            false,
            null,
            List.of(),
            null,
            null,
            "not-needed",
            null,
            null,
            null,
            null,
            null,
            null,
            null,
            null);

    assertThatThrownBy(() -> service.submit(orphan))
        .isInstanceOf(BusinessException.class)
        .hasMessageContaining("세대를 찾을 수 없습니다");
  }

  /* ------------------------------ 픽스처 ------------------------------ */

  private VisitSubmission accepted(
      int roomCount,
      String mfgYm,
      Integer replaceCount,
      List<ReplacementInput> items,
      String rxDoneCode) {
    return accepted(roomCount, mfgYm, false, replaceCount, items, rxDoneCode);
  }

  private VisitSubmission accepted(
      int roomCount,
      String mfgYm,
      boolean mfgUnmarked,
      Integer replaceCount,
      List<ReplacementInput> items,
      String rxDoneCode) {
    return accepted(
        roomCount, mfgYm, mfgUnmarked, replaceCount, items, rxDoneCode, "not-needed", null);
  }

  private VisitSubmission accepted(
      int roomCount,
      String mfgYm,
      boolean mfgUnmarked,
      Integer replaceCount,
      List<ReplacementInput> items,
      String rxDoneCode,
      String revisitPlanCode,
      String noRevisitNote) {
    return new VisitSubmission(
        unitId,
        officerId,
        null,
        "accepted",
        "owner",
        null,
        null,
        roomCount,
        mfgYm,
        mfgUnmarked,
        replaceCount,
        items,
        "installed",
        rxDoneCode,
        revisitPlanCode,
        noRevisitNote,
        null,
        null,
        null,
        null,
        null,
        null,
        null);
  }

  private static VisitSubmission withKey(VisitSubmission s, UUID key) {
    return new VisitSubmission(
        s.unitId(),
        s.officerId(),
        key,
        s.consentCode(),
        s.respondentTypeCode(),
        s.refusalReasonCode(),
        s.refusalNote(),
        s.roomCount(),
        s.mfgYm(),
        s.mfgUnmarked(),
        s.replaceCount(),
        s.replacements(),
        s.extinguisherInstalledCode(),
        s.rxDoneCode(),
        s.revisitPlanCode(),
        s.noRevisitNote(),
        s.note(),
        s.routeOrder(),
        s.dispatchedScore(),
        s.dispatchedOrderKey(),
        s.scoreVersion(),
        s.gpsLat(),
        s.gpsLng());
  }
}
