# 배포(Railway)
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
  docker:
    compose:
      enabled: false
  jpa:
    show-sql: false

# 배포 URL에 springdoc 노출 X.
springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
